% OMTConfigurationGenerator
% This script is used to generate .mat files with OMTConfigurations
clear; close all; clc;

%% Set the OMT Parameters
% Format: Nx3 cell array, where N are the number of messages defined
% First column: OMT Number as an integer
% Second column: Length of OMT Data in bits as an integer
% Third column: Short description of the OMT as a character string
% Fourth column: List of defined groups of messages
%
% Ex: omtConfig = {1, 224, 'ECDSA level 2 public key';...
%                  2, 768, 'ECDSA level 1 signature of level 2 public key';...
%                  ...etc.}
%
% Notes: - For fields that have no defined bit structure yet, leave 2nd
%          column as []

%% ECSchnorr_RevA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OMTConfiguration Filename
filename = 'ECSchnorr_RevA';

level2PublicKeyLengthBits = 224;
level1PublicKeyLengthBits = 384;
encryptionKeyLengthBits = 256;

% Define first three columns
omtConfig = {...
    1, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECSchnorr current level-2 public key w/ level-1 signature';...
    2, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECSchnorr next level 2 public key w/ level-1 signature';...
    3, 34*2 + level1PublicKeyLengthBits*3/2, 'Expiration time of current level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
    4, 34*2 + level1PublicKeyLengthBits*3/2, 'Expiration time of next level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
    5, encryptionKeyLengthBits, 'Encryption keys to unlock current level-1 public keys';...
    6, encryptionKeyLengthBits, 'Encryption keys to unlock next level-1 public keys';...
    7, 0, 'Reserved';...
    };

% Define final column for message groupings
omtConfig = [omtConfig,...
    {{'Total', 'Authenticated current level 2 key'};... % 1
    {'Total', 'Authenticated next level 2 key'};... % 2
    {'Total', 'Expiration of current keys'};... % 3
    {'Total', 'Expiration of next keys'};... % 4
    {'Total', 'Authenticated current level 1 key'};... % 5
    {'Total', 'Authenticated next level 1 key'};... % 6
    {};... %7
    }];

notes = 'Concatenated keys and sigs and switched to encryption for level 1';

%% Complete sanity check on input values
% Check to make sure that OMTNum are valid and non-repeated
if any(cell2mat(omtConfig(:,1)) < 0)
    error('Only positive integers are valid OTAR Message Type numbers')
end
if any(~isequal(cell2mat(omtConfig(:,1)), floor(cell2mat(omtConfig(:,1)))))
    error('Only positive integers are valid OTAR Message Type numbers')
end
if (length(cell2mat(omtConfig(:,1))) ~= length(unique(cell2mat(omtConfig(:,1)))))
    error('OTAR Message Type numbers must be non-repeating')
end

%% Save OMTConfiguration File
currentDir = pwd;

% Change path to save data in OMTConfigurationFiles directory
cd ..
cd OMTConfigurationFiles
save(filename, 'omtConfig', 'notes')     % Save only omtConfig variable and notes
cd(currentDir)
cd ..

%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Past Iterations %%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% ECDSA_RevA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'ECDSA_RevA';
% 
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% 
% % Define first three columns
% omtConfig = {...
%     1, level2PublicKeyLengthBits, 'ECDSA current level 2 public key';...
%     2, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of current level 2 public key';...
%     3, 34*2, 'Expiration time of current level 2 public key and level 1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys.';...
%     4, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 3';...
%     5, level2PublicKeyLengthBits, 'ECDSA next level 2 public key';...
%     6, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 5';...
%     7, 34*2, 'Expiration time of next level 2 public key and level 1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys.';...
%     8, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 7';...
%     9, 0, 'Reserved';...
%     10, 0, 'Reserved';...
%     11, 0, 'Reserved';...
%     12, level1PublicKeyLengthBits, 'ECDSA level 1 current public key';...
%     13, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 12, self-signed public key';...
%     14, level1PublicKeyLengthBits, 'ECDSA level 1 next public key';...
%     15, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 14';...
%     };
% 
% % Define final column for message groupings
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current level 2 key'};... % 1
%     {'Total', 'Authenticated current level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Expiration of current keys'};... % 4
%     {'Total', 'Authenticated next level 2 key'};... % 5
%     {'Total', 'Authenticated next level 2 key'};... % 6
%     {'Total', 'Expiration of next keys'};... % 7
%     {'Total', 'Expiration of next keys'};... % 8
%     {};... % 9
%     {};... % 10
%     {};... % 11
%     {'Total', 'Authenticated current level 1 key'};... % 12
%     {'Total', 'Authenticated current level 1 key'};... % 13
%     {'Total', 'Authenticated next level 1 key'};... % 14
%     {'Total', 'Authenticated next level 1 key'}... % 15
%     }];

%% TESLA_RevA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'TESLA_RevA';
% 
% teslaKeyLengthBits = 115;
% teslaSaltLengthBits = 30;
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% 
% % Define first three columns
% omtConfig = {...
%     1, teslaKeyLengthBits + teslaSaltLengthBits, 'TESLA current keychain root/intermediate key and salt';...
%     2, level2PublicKeyLengthBits*2, 'ECDSA level 2 signature of current TESLA keychain';...
%     3, level2PublicKeyLengthBits, 'ECDSA current level 2 public key';...
%     4, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 3';...
%     5, 34*3, 'Expiration time of current level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys.';...
%     6, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 5';...
%     7, 0, 'Reserved';...
%     8, 0, 'Reserved';...
%     9, teslaKeyLengthBits + teslaSaltLengthBits, 'TESLA next keychain root/intermediate key and salt';...
%     10, level2PublicKeyLengthBits*2, 'ECDSA level 2 signature of next TESLA keychain';...
%     11, level2PublicKeyLengthBits, 'ECDSA next level 2 public key';...
%     12, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 11';...
%     13, 34*3, 'Expiration time of next level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys.';...
%     14, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 13';...
%     15, 0, 'Reserved';...
%     16, 0, 'Reserved';...
%     17, 0, 'Reserved';...
%     18, 0, 'Reserved';...
%     19, 0, 'Reserved';...
%     20, 0, 'Reserved';...
%     21, 0, 'Reserved';...
%     22, 0, 'Reserved';...
%     23, 0, 'Reserved';...
%     24, 0, 'Reserved';...
%     25, 0, 'Reserved';...
%     26, 0, 'Reserved';...
%     27, 0, 'Reserved';...
%     28, level1PublicKeyLengthBits, 'ECDSA level 1 current public key';...
%     29, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 28, self-signed public key';...
%     30, level1PublicKeyLengthBits, 'ECDSA level 1 next public key';...
%     31, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 31';...
%     };
% 
% % Define final column for message groupings
% %
% % Note: MESSAGE GROUPS MUST HAVE THE SAME NAME AS THOSE IN 
% % PlottingParameters in config.m
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current TESLA keychain and salt'};... % 1
%     {'Total', 'Authenticated current TESLA keychain and salt'};... % 2
%     {'Total', 'Authenticated current level 2 key'};... % 3
%     {'Total', 'Authenticated current level 2 key'};... % 4
%     {'Total', 'Expiration of current keys'};... % 5
%     {'Total', 'Expiration of current keys'};... % 6
%     {};... % 7
%     {};... % 8
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 9
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 10
%     {'Total', 'Authenticated next level 2 key'};... % 11
%     {'Total', 'Authenticated next level 2 key'};... % 12
%     {'Total', 'Expiration of next keys'};... % 13
%     {'Total', 'Expiration of next keys'};... % 14
%     {};... % 15
%     {};... % 16
%     {};... % 17
%     {};... % 18
%     {};... % 19
%     {};... % 20
%     {};... % 21
%     {};... % 22
%     {};... % 23
%     {};... % 24
%     {};... % 25
%     {};... % 26
%     {};... % 27
%     {'Total', 'Authenticated current level 1 key'};... % 28
%     {'Total', 'Authenticated current level 1 key'};... % 29
%     {'Total', 'Authenticated next level 1 key'};... % 30
%     {'Total', 'Authenticated next level 1 key'};... % 31
%     }];

%% ECDSA_RevB %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'ECDSA_RevB';
% 
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% 
% % Define first three columns
% omtConfig = {...
%     1, level2PublicKeyLengthBits + 1, 'ECDSA current level 2 public key';...
%     2, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of current level 2 public key';...
%     3, 34*2, 'Expiration time of current level 2 public key and level 1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys.';...
%     4, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 3';...
%     5, level2PublicKeyLengthBits + 1, 'ECDSA next level 2 public key';...
%     6, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 5';...
%     7, 34*2, 'Expiration time of next level 2 public key and level 1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys.';...
%     8, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 7';...
%     9, 0, 'Reserved';...
%     10, 0, 'Reserved';...
%     11, 0, 'Reserved';...
%     12, level1PublicKeyLengthBits + 1, 'ECDSA level 1 current public key';...
%     13, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 12, self-signed public key';...
%     14, level1PublicKeyLengthBits + 1, 'ECDSA level 1 next public key';...
%     15, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 14';...
%     };
% 
% % Define final column for message groupings
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current level 2 key'};... % 1
%     {'Total', 'Authenticated current level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Expiration of current keys'};... % 4
%     {'Total', 'Authenticated next level 2 key'};... % 5
%     {'Total', 'Authenticated next level 2 key'};... % 6
%     {'Total', 'Expiration of next keys'};... % 7
%     {'Total', 'Expiration of next keys'};... % 8
%     {};... % 9
%     {};... % 10
%     {};... % 11
%     {'Total', 'Authenticated current level 1 key'};... % 12
%     {'Total', 'Authenticated current level 1 key'};... % 13
%     {'Total', 'Authenticated next level 1 key'};... % 14
%     {'Total', 'Authenticated next level 1 key'}... % 15
%     }];
% 
% notes = 'Added extra bit to public key length to take away ambiguity of y-value';

%% TESLA_RevB %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'TESLA_RevB';
% 
% teslaKeyLengthBits = 115;
% teslaSaltLengthBits = 30;
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% 
% % Define first three columns
% omtConfig = {...
%     1, teslaKeyLengthBits + teslaSaltLengthBits, 'TESLA current keychain root/intermediate key and salt';...
%     2, level2PublicKeyLengthBits*2, 'ECDSA level 2 signature of current TESLA keychain';...
%     3, level2PublicKeyLengthBits + 1, 'ECDSA current level 2 public key';...
%     4, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 3';...
%     5, 34*3, 'Expiration time of current level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys.';...
%     6, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 5';...
%     7, 0, 'Reserved';...
%     8, 0, 'Reserved';...
%     9, teslaKeyLengthBits + teslaSaltLengthBits, 'TESLA next keychain root/intermediate key and salt';...
%     10, level2PublicKeyLengthBits*2, 'ECDSA level 2 signature of next TESLA keychain';...
%     11, level2PublicKeyLengthBits + 1, 'ECDSA next level 2 public key';...
%     12, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 11';...
%     13, 34*3, 'Expiration time of next level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys.';...
%     14, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 13';...
%     15, 0, 'Reserved';...
%     16, 0, 'Reserved';...
%     17, 0, 'Reserved';...
%     18, 0, 'Reserved';...
%     19, 0, 'Reserved';...
%     20, 0, 'Reserved';...
%     21, 0, 'Reserved';...
%     22, 0, 'Reserved';...
%     23, 0, 'Reserved';...
%     24, 0, 'Reserved';...
%     25, 0, 'Reserved';...
%     26, 0, 'Reserved';...
%     27, 0, 'Reserved';...
%     28, level1PublicKeyLengthBits + 1, 'ECDSA level 1 current public key';...
%     29, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 28, self-signed public key';...
%     30, level1PublicKeyLengthBits + 1, 'ECDSA level 1 next public key';...
%     31, level1PublicKeyLengthBits*2, 'ECDSA level 1 signature of OMT 31';...
%     };
% 
% % Define final column for message groupings
% %
% % Note: MESSAGE GROUPS MUST HAVE THE SAME NAME AS THOSE IN 
% % PlottingParameters in config.m
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current TESLA keychain and salt'};... % 1
%     {'Total', 'Authenticated current TESLA keychain and salt'};... % 2
%     {'Total', 'Authenticated current level 2 key'};... % 3
%     {'Total', 'Authenticated current level 2 key'};... % 4
%     {'Total', 'Expiration of current keys'};... % 5
%     {'Total', 'Expiration of current keys'};... % 6
%     {};... % 7
%     {};... % 8
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 9
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 10
%     {'Total', 'Authenticated next level 2 key'};... % 11
%     {'Total', 'Authenticated next level 2 key'};... % 12
%     {'Total', 'Expiration of next keys'};... % 13
%     {'Total', 'Expiration of next keys'};... % 14
%     {};... % 15
%     {};... % 16
%     {};... % 17
%     {};... % 18
%     {};... % 19
%     {};... % 20
%     {};... % 21
%     {};... % 22
%     {};... % 23
%     {};... % 24
%     {};... % 25
%     {};... % 26
%     {};... % 27
%     {'Total', 'Authenticated current level 1 key'};... % 28
%     {'Total', 'Authenticated current level 1 key'};... % 29
%     {'Total', 'Authenticated next level 1 key'};... % 30
%     {'Total', 'Authenticated next level 1 key'};... % 31
%     }];
% 
% notes = 'Added extra bit to public key length to take away ambiguity of y-value';

%% ECDSA_RevC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'ECDSA_RevC';
% 
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% encryptionKeyLengthBits = 256;
% 
% % Define first three columns
% omtConfig = {...
%     1, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*2, 'ECDSA current level-2 public key w/ level-1 signature';...
%     2, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*2, 'ECDSA next level 2 public key w/ level-1 signature';...
%     3, 34*2 + level1PublicKeyLengthBits*2, 'Expiration time of current level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
%     4, 34*2 + level1PublicKeyLengthBits*2, 'Expiration time of next level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
%     5, encryptionKeyLengthBits, 'Encryption keys to unlock current level-1 public keys';...
%     6, encryptionKeyLengthBits, 'Encryption keys to unlock next level-1 public keys';...
%     7, 0, 'Reserved';...
%     };
% 
% % Define final column for message groupings
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current level 2 key'};... % 1
%     {'Total', 'Authenticated next level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Expiration of next keys'};... % 4
%     {'Total', 'Authenticated current level 1 key'};... % 5
%     {'Total', 'Authenticated next level 1 key'};... % 6
%     {};... %7
%     }];
% 
% notes = 'Concatenated keys and sigs and switched to encryption for level 1';

%% TESLA_RevC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'TESLA_RevC';
% 
% teslaKeyLengthBits = 115;
% teslaSaltLengthBits = 30;
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% encryptionKeyLengthBits = 256;
% 
% % Define first three columns
% omtConfig = {...
%     1, teslaKeyLengthBits + teslaSaltLengthBits + level2PublicKeyLengthBits*2, 'TESLA current keychain root/intermediate key, salt, and level 2 signature';...
%     2, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*2, 'ECDSA current level 2 public key with ECDSA level 1 signature';...
%     3, 34*3 + level1PublicKeyLengthBits*2, 'Expiration time of current level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys. With ECDSA level 1 signature';...
%     4, teslaKeyLengthBits + teslaSaltLengthBits + level2PublicKeyLengthBits*2, 'TESLA next keychain root/intermediate key, salt, and level 2 signature';...
%     5, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*2, 'ECDSA next level 2 public key with ECDSA level 1 signature';...
%     6, 34*3 + level1PublicKeyLengthBits*2, 'Expiration time of next level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys. With ECDSA level 1 signature';...
%     7, 0, 'Reserved';...
%     8, encryptionKeyLengthBits, 'Encryption key to unlock current level-1 public key';...
%     9, encryptionKeyLengthBits, 'Encryption key to unlock next level-1 public key';...
%     10, 0, 'Reserved';...
%     11, 0, 'Reserved';...
%     12, 0, 'Reserved';...
%     13, 0, 'Reserved';...
%     14, 0, 'Reserved';...
%     15, 0, 'Reserved';...
%     };
% 
% % Define final column for message groupings
% %
% % Note: MESSAGE GROUPS MUST HAVE THE SAME NAME AS THOSE IN 
% % PlottingParameters in config.m
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current TESLA keychain and salt'};... % 1
%     {'Total', 'Authenticated current level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 4
%     {'Total', 'Authenticated next level 2 key'};... % 5
%     {'Total', 'Expiration of next keys'};... % 6
%     {};... % 7
%     {'Total', 'Authenticated current level 1 key'};... % 8
%     {'Total', 'Authenticated next level 1 key'};... % 9
%     {};... % 10
%     {};... % 11
%     {};... % 12
%     {};... % 13
%     {};... % 14
%     {};... % 15
%     }];
% 
% notes = 'Concatenated keys and sigs and switched to encryption for level 1';

% %% TESLA_RevC_ECSchnorr %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'TESLA_RevC_ECSchnorr';
% 
% teslaKeyLengthBits = 115;
% teslaSaltLengthBits = 30;
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% encryptionKeyLengthBits = 256;
% 
% % Define first three columns
% omtConfig = {...
%     1, teslaKeyLengthBits + teslaSaltLengthBits + level2PublicKeyLengthBits*2, 'TESLA current keychain root/intermediate key, salt, and level 2 signature';...
%     2, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECDSA current level 2 public key with ECDSA level 1 signature';...
%     3, 34*3 + level1PublicKeyLengthBits*3/2, 'Expiration time of current level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys. With ECDSA level 1 signature';...
%     4, teslaKeyLengthBits + teslaSaltLengthBits + level2PublicKeyLengthBits*3/2, 'TESLA next keychain root/intermediate key, salt, and level 2 signature';...
%     5, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECDSA next level 2 public key with ECDSA level 1 signature';...
%     6, 34*3 + level1PublicKeyLengthBits*3/2, 'Expiration time of next level 1 and level 2 public key and TESLA keychain, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x3 for all keys. With ECDSA level 1 signature';...
%     7, 0, 'Reserved';...
%     8, encryptionKeyLengthBits, 'Encryption key to unlock current level-1 public key';...
%     9, encryptionKeyLengthBits, 'Encryption key to unlock next level-1 public key';...
%     10, 0, 'Reserved';...
%     11, 0, 'Reserved';...
%     12, 0, 'Reserved';...
%     13, 0, 'Reserved';...
%     14, 0, 'Reserved';...
%     15, 0, 'Reserved';...
%     };
% 
% % Define final column for message groupings
% %
% % Note: MESSAGE GROUPS MUST HAVE THE SAME NAME AS THOSE IN 
% % PlottingParameters in config.m
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current TESLA keychain and salt'};... % 1
%     {'Total', 'Authenticated current level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Authenticated next TESLA keychain and salt'};... % 4
%     {'Total', 'Authenticated next level 2 key'};... % 5
%     {'Total', 'Expiration of next keys'};... % 6
%     {};... % 7
%     {'Total', 'Authenticated current level 1 key'};... % 8
%     {'Total', 'Authenticated next level 1 key'};... % 9
%     {};... % 10
%     {};... % 11
%     {};... % 12
%     {};... % 13
%     {};... % 14
%     {};... % 15
%     }];
% 
% notes = 'Concatenated keys and sigs and switched to encryption for level 1';

% %% ECSchnorr_RevA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % OMTConfiguration Filename
% filename = 'ECSchnorr_RevA';
% 
% level2PublicKeyLengthBits = 224;
% level1PublicKeyLengthBits = 384;
% encryptionKeyLengthBits = 256;
% 
% % Define first three columns
% omtConfig = {...
%     1, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECSchnorr current level-2 public key w/ level-1 signature';...
%     2, level2PublicKeyLengthBits + 1 + level1PublicKeyLengthBits*3/2, 'ECSchnorr next level 2 public key w/ level-1 signature';...
%     3, 34*2 + level1PublicKeyLengthBits*3/2, 'Expiration time of current level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
%     4, 34*2 + level1PublicKeyLengthBits*3/2, 'Expiration time of next level-2 public key and level-1 public key, 34 = 20 TOW + 10 GPS WN + 4 Rollover. x2 for both levels of keys. w/ level-1 signature';...
%     5, encryptionKeyLengthBits, 'Encryption keys to unlock current level-1 public keys';...
%     6, encryptionKeyLengthBits, 'Encryption keys to unlock next level-1 public keys';...
%     7, 0, 'Reserved';...
%     };
% 
% % Define final column for message groupings
% omtConfig = [omtConfig,...
%     {{'Total', 'Authenticated current level 2 key'};... % 1
%     {'Total', 'Authenticated next level 2 key'};... % 2
%     {'Total', 'Expiration of current keys'};... % 3
%     {'Total', 'Expiration of next keys'};... % 4
%     {'Total', 'Authenticated current level 1 key'};... % 5
%     {'Total', 'Authenticated next level 1 key'};... % 6
%     {};... %7
%     }];
% 
% notes = 'Concatenated keys and sigs and switched to encryption for level 1';














